name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
        npm ci
        npm run build
        npm run deploy

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      run:
        npm run deploy
      with:
        folder: dist/crud-app/
        branch: gh-pages
